messages:
  start: "&cСтример &f{player} &cначал стрим: &9&n{link}{desc}"
  desc: " &7({desc})"
  stop: "&aСтрим завершён!"
  no_permission: "&cУ вас нет прав на использование этой команды!"
  not_streaming: "&eВы не находитесь в эфире."
  need_link: "&eУкажите ссылку на твич: /стрим <ссылка>"
  usage: "&eИспользуйте: /стрим <ссылка> или /стрим стоп"
  only_player: "&cТолько игрок может использовать эту команду!"
  invalid_link: "&cВведите корректную ссылку на Twitch!"
  show_streamer: "§aTwitch канал &f{player} §f{desc}- &9{link}"
  streamer_not_found: "§cСтример не найден!"
  streamer_added: "§aСтример {player} (Twitch: {desc}) добавлен!"
  no_add_permission: "§cУ вас нет прав на добавление стримеров!"
  no_remove_permission: "§cУ вас нет прав на удаление стримеров!"
  streamer_removed: "§aСтример {player} удалён!"
  streamer_list_header: "Список стримеров"
  streamer_list_entry: "§b• §a{player} §7(§5Twitch: {desc}§7) \n&9{link}"
  stream_manual_broadcast: "§d[СТРИМ] §a{player} §7— §f{desc}\n&9{link}"
  no_reload_permission: "§cУ вас нет прав на перезагрузку!"
  reload_success: "§aКонфиг Twitch перезагружен!"
  streamer_status_online: "§aСтример {player} сейчас В ЭФИРЕ!"
  streamer_status_offline: "§eСтример {player} сейчас оффлайн."
  stream_start_broadcast: "§d[СТРИМ] §a{player} §fначал стрим\n&9{link}"
  stream_repeat_broadcast: "§d[СТРИМ] §a{player} §fстрим: &9{link}"
  streamers_online_header: "§d[СТРИМ] §fСейчас в эфире:"
  streamers_online_none: "§d[СТРИМ] §7Сейчас никто не стримит."
  streamers_online_entry: "§b• §a{player} §7(§5Twitch: {desc}§7)"

twitch:
  # группа, которая выдается стримеру, когда он на стриме
  group: "ГРУППА LUCKPERMS"
  # ID клиента Twitch
  client_id: "ВАШ КЛИЕНТ ID"
  # Токен OAuth
  oauth_token: "ВАШ ТОКЕН"
  # Период проверки стримов (в тиках)
  stream_check_period: 1200 # 60 секунд
  # Период анонса стримеров (в тиках)
  announce_period: 72000 # 1 час
  streamers: []
